### PR TITLE
Fix: name property should configure App name

### LINKED ISSUE #19: Name can't be set via programmatic configuration
Hello everyone!

I'm trying to use hazelcast-eureka-one and hazelcast only programmatically, since I'm using Spring for my DI with the hazelcast-spring.jar, it's enough to configure the appropriate Config Bean and Spring would create a hazelcast instance for me. But whatever I do, I can't seem to get the name of the eureka client instance right.

My setup is: Maven Dependencies
```xml
<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
            <version>2.0.1.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast</artifactId>
            <version>3.9.3</version>
        </dependency>
        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast-spring</artifactId>
            <version>3.9.3</version>
        </dependency>
        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast-eureka-one</artifactId>
            <version>1.0.2</version>
        </dependency>
    </dependencies>
```

With the following Config Bean configuration:

```kotlin
@Configuration
class CacheConfiguration {
    @Bean
    fun configuration(
            @Value("\${eureka.client.serviceUrl.defaultZone:http://127.0.0.1:8761/eureka/}") eurekaServiceUrl: String): Config {
        val config = Config()
        val mapConfig = MapConfig("priorities")
                .setTimeToLiveSeconds(10 * 60)
                .setEvictionPolicy(EvictionPolicy.LRU)
                .setMaxSizeConfig(MaxSizeConfig(10, MaxSizeConfig.MaxSizePolicy.FREE_HEAP_SIZE))
        config.addMapConfig(mapConfig)

        val networkConfig = NetworkConfig()
        val joinConfig = JoinConfig()
        val awsConfig = AwsConfig()
        awsConfig.isEnabled = false
        joinConfig.awsConfig = awsConfig
        val tcpIpConfig = TcpIpConfig()
        tcpIpConfig.isEnabled = false
        joinConfig.tcpIpConfig = tcpIpConfig
        val multicastConfig = MulticastConfig()
        multicastConfig.isEnabled = false
        joinConfig.multicastConfig = multicastConfig

        val eurekaDiscoveryConfig = DiscoveryConfig()
        val eurekaDiscoveryStrategyConfig = DiscoveryStrategyConfig(com.hazelcast.eureka.one.EurekaOneDiscoveryStrategyFactory(),
                mapOf(
                        "use-classpath-eureka-client-props" to false,
                        "shouldUseDns" to false,
                        "name" to "hazelcast-cache-cluster",
                        "serviceUrl.default" to eurekaServiceUrl
                ) as Map<String, Comparable<Any?>>?)
        eurekaDiscoveryConfig.discoveryStrategyConfigs.add(eurekaDiscoveryStrategyConfig)
        
        joinConfig.discoveryConfig = eurekaDiscoveryConfig
        networkConfig.join = joinConfig
        config.networkConfig = networkConfig

        config.setProperty("hazelcast.discovery.enabled", "true")

        return config
    }
}
```

So this setup basically works fine, its just that the name of the eureka instance is always UNKNOWN.
When i have eureka-client.properties in place, it just works as expected and the name of the eureka client instance is set correctly.

```properties
hazelcast.shouldUseDns=false
hazelcast.name=hazelcast-cache-cluster
hazelcast.serviceUrl.default=http://127.0.0.1:8761/eureka/
```

Now i debugged through this a little, and the cause seems to be that the name property gets filtered out as to when it gets passed down to the discovery strategy, and I also now know that the file based approach works cause when `MyDataCenterInstanceConfig` is instantiated, it passes the namespace to the `PropertiesInstanceConfig` which in turn uses the `Archaius1Utils.initConfig(CommonConstants.CONFIG_FILE_NAME)` method call to search for the properties file "eureka-client" on the classpath and read the data.

The problem for me now is that I would also like to set a name programmatically, but I really have no clue on how this should be fixed, or even if it is supposed to be this way?

Anyways, thanks for any help in advance!

### PR DESCRIPTION
**Pull request by googlielmo**
Fix #19 
 - name property now configures App name as expected with programmatic configuration

### CODE REVIEW

File: src/main/java/com/hazelcast/eureka/one/EurekaOneDiscoveryStrategy.java [hunk 1]
```diff
@@ -389,19 +393,28 @@ public boolean shouldRegisterWithEureka() {
         private final EurekaInstanceConfig instanceConfig;
         private final DiscoveryNode localNode;
         private final String uuid;
+        private final String appname;
 
         private DelegatingInstanceConfig(EurekaInstanceConfig instanceConfig, DiscoveryNode localNode) {
             this.instanceConfig = instanceConfig;
             this.localNode = localNode;
             this.uuid = UuidUtil.newSecureUuidString();
+            this.appname = instanceConfig.getAppname();
```
Comment (leszko) [inline src/main/java/com/hazelcast/eureka/one/EurekaOneDiscoveryStrategy.java]: Super minor: you could have the following line instead of these 4.
```java
this(instanceConfig, localNode, instanceConfig.getAppname());
```

File: src/main/java/com/hazelcast/eureka/one/EurekaOneDiscoveryStrategy.java [hunk 2]
```diff
@@ -225,12 +224,17 @@ private EurekaInstanceConfig buildInstanceConfig(DiscoveryNode localNode) {
...
             }
             if ("cloud".equals(value.trim().toLowerCase())) {
                 return new DelegatingInstanceConfig(new CloudInstanceConfig(this.namespace), localNode);
             }
-            return new DelegatingInstanceConfig(new MyDataCenterInstanceConfig(this.namespace), localNode);
+            if (this.useClasspathEurekaClientProps) {
+                return new DelegatingInstanceConfig(new MyDataCenterInstanceConfig(this.namespace), localNode);
+            }
+            else {
+                return new DelegatingInstanceConfig(new MyDataCenterInstanceConfig(this.namespace), localNode, getAppname());
```
Comment (leszko) [inline src/main/java/com/hazelcast/eureka/one/EurekaOneDiscoveryStrategy.java]: Do you think it would be possible (in a simple manner) to add a unit test to cover this line you added?

**Comment by googlielmo** [comment]
verify

File: src/main/java/com/hazelcast/eureka/one/EurekaOneDiscoveryStrategy.java (hunk 2 above)
Comment (googlielmo) [reply src/main/java/com/hazelcast/eureka/one/EurekaOneDiscoveryStrategy.java]: Not so easily, at the moment mocks are used throughout tests, thus preventing real testing of instance-config classes, not only this one. I'll add an issue.

File: src/main/java/com/hazelcast/eureka/one/EurekaOneDiscoveryStrategy.java (hunk 1 above)
Comment (googlielmo) [reply src/main/java/com/hazelcast/eureka/one/EurekaOneDiscoveryStrategy.java]: good spot, thanks
